# Builds and tests a Java program with Gradle

stages:
  - build

build:
  stage: build
  image: gradle:5.1-jdk11-slim
  script:
    - java -version
    # Uncomment if you want to build using gradle wrapper
    # - chmod +x gradlew
    # ./gradlew build
    - gradle build
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
      paths:
        - build/reports/
