# Builds and tests a Java program with Gradle

stages:
  - build

build:
  stage: build
  image: gradle:jdk10-slim
  script:
    - java -version
    # Uncomment if you want to build using gradle wrapper
    # - chmod +x gradlew
    - gradle build
